### ISSUE TITLE
Data type of column should be made uppercase to avoid "data type can't be blank" error message.

### ISSUE THREAD

**Issue by callmedeeray** [drzax/morphio-wdc#1]
Please forgive me as I'm quite Git-challenged:  I'd have submitted my own fix to the code but I am not comfortable trying that since I've never done it before.  

However, I DO know my way around a Web Data Connector, so I tested this in the simulator, as well as deployed it to my own repo and tested it in Tableau, and it works.

Teeny tiny bug:  the data type of the table column should be put in uppercase before being passed to the typesMap.

Easy fix though:  just change line 44 of morph.js to `dataType: typesMap[table.type.toUpperCase()]`

Good luck and thank you so much for this wdc!!

**Comment by drzax** [comment]
Oh, cool. Thanks for the fix. If it's in your own repo on GitHub, you should be able to easily create a pull request and I'll merge it here. That way you'll get credit for the change too. 

Otherwise, I'm happy to update. I haven't needed this in a while, so nice to know it's being used.

**Comment by callmedeeray** [comment]
I don't feel the need to get any credit - please feel free to update!
